//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRevenge.SOAPTest.ServiceHorario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/TheRevenge.Data.Dominio")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_HorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Horario {
            get {
                return this.Id_HorarioField;
            }
            set {
                if ((this.Id_HorarioField.Equals(value) != true)) {
                    this.Id_HorarioField = value;
                    this.RaisePropertyChanged("Id_Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Val_Hor {
            get {
                return this.Val_HorField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_HorField, value) != true)) {
                    this.Val_HorField = value;
                    this.RaisePropertyChanged("Val_Hor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHorario.IHorariosService")]
    public interface IHorariosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorariosService/ListarHorario", ReplyAction="http://tempuri.org/IHorariosService/ListarHorarioResponse")]
        TheRevenge.SOAPTest.ServiceHorario.Horario[] ListarHorario();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHorariosServiceChannel : TheRevenge.SOAPTest.ServiceHorario.IHorariosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorariosServiceClient : System.ServiceModel.ClientBase<TheRevenge.SOAPTest.ServiceHorario.IHorariosService>, TheRevenge.SOAPTest.ServiceHorario.IHorariosService {
        
        public HorariosServiceClient() {
        }
        
        public HorariosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorariosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorariosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorariosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TheRevenge.SOAPTest.ServiceHorario.Horario[] ListarHorario() {
            return base.Channel.ListarHorario();
        }
    }
}
