//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRevenge.SOAPTest.ServiceEstadoCita {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCita", Namespace="http://schemas.datacontract.org/2004/07/TheRevenge.Data.Dominio")]
    [System.SerializableAttribute()]
    public partial class EstadoCita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Estado {
            get {
                return this.Id_EstadoField;
            }
            set {
                if ((this.Id_EstadoField.Equals(value) != true)) {
                    this.Id_EstadoField = value;
                    this.RaisePropertyChanged("Id_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Val_Estado {
            get {
                return this.Val_EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_EstadoField, value) != true)) {
                    this.Val_EstadoField = value;
                    this.RaisePropertyChanged("Val_Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstadoCita.IEstadoCitasService")]
    public interface IEstadoCitasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoCitasService/ListarEstadoCita", ReplyAction="http://tempuri.org/IEstadoCitasService/ListarEstadoCitaResponse")]
        TheRevenge.SOAPTest.ServiceEstadoCita.EstadoCita[] ListarEstadoCita();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadoCitasServiceChannel : TheRevenge.SOAPTest.ServiceEstadoCita.IEstadoCitasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoCitasServiceClient : System.ServiceModel.ClientBase<TheRevenge.SOAPTest.ServiceEstadoCita.IEstadoCitasService>, TheRevenge.SOAPTest.ServiceEstadoCita.IEstadoCitasService {
        
        public EstadoCitasServiceClient() {
        }
        
        public EstadoCitasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoCitasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoCitasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoCitasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TheRevenge.SOAPTest.ServiceEstadoCita.EstadoCita[] ListarEstadoCita() {
            return base.Channel.ListarEstadoCita();
        }
    }
}
