
package pe.com.consultorio.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PacientesService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://127.0.0.1:1425/PacientesService.svc?wsdl")
public class PacientesService
    extends Service
{

    private final static URL PACIENTESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PACIENTESSERVICE_EXCEPTION;
    private final static QName PACIENTESSERVICE_QNAME = new QName("http://tempuri.org/", "PacientesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1425/PacientesService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PACIENTESSERVICE_WSDL_LOCATION = url;
        PACIENTESSERVICE_EXCEPTION = e;
    }

    public PacientesService() {
        super(__getWsdlLocation(), PACIENTESSERVICE_QNAME);
    }

    public PacientesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PACIENTESSERVICE_QNAME, features);
    }

    public PacientesService(URL wsdlLocation) {
        super(wsdlLocation, PACIENTESSERVICE_QNAME);
    }

    public PacientesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PACIENTESSERVICE_QNAME, features);
    }

    public PacientesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PacientesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService")
    public IPacientesService getBasicHttpBindingIPacientesService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPacientesService"), IPacientesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPacientesService
     */
    @WebEndpoint(name = "BasicHttpBinding_IPacientesService")
    public IPacientesService getBasicHttpBindingIPacientesService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPacientesService"), IPacientesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PACIENTESSERVICE_EXCEPTION!= null) {
            throw PACIENTESSERVICE_EXCEPTION;
        }
        return PACIENTESSERVICE_WSDL_LOCATION;
    }

}
