
package pe.com.consultorio.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TiposDocService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://127.0.0.1:1425/TiposDocService.svc?wsdl")
public class TiposDocService
    extends Service
{

    private final static URL TIPOSDOCSERVICE_WSDL_LOCATION;
    private final static WebServiceException TIPOSDOCSERVICE_EXCEPTION;
    private final static QName TIPOSDOCSERVICE_QNAME = new QName("http://tempuri.org/", "TiposDocService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1425/TiposDocService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIPOSDOCSERVICE_WSDL_LOCATION = url;
        TIPOSDOCSERVICE_EXCEPTION = e;
    }

    public TiposDocService() {
        super(__getWsdlLocation(), TIPOSDOCSERVICE_QNAME);
    }

    public TiposDocService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIPOSDOCSERVICE_QNAME, features);
    }

    public TiposDocService(URL wsdlLocation) {
        super(wsdlLocation, TIPOSDOCSERVICE_QNAME);
    }

    public TiposDocService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIPOSDOCSERVICE_QNAME, features);
    }

    public TiposDocService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TiposDocService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITiposDocService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITiposDocService")
    public ITiposDocService getBasicHttpBindingITiposDocService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITiposDocService"), ITiposDocService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITiposDocService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITiposDocService")
    public ITiposDocService getBasicHttpBindingITiposDocService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITiposDocService"), ITiposDocService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIPOSDOCSERVICE_EXCEPTION!= null) {
            throw TIPOSDOCSERVICE_EXCEPTION;
        }
        return TIPOSDOCSERVICE_WSDL_LOCATION;
    }

}
