//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheRevenge.SOAPTest.ServicePaciente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://schemas.datacontract.org/2004/07/TheRevenge.Data.Dominio")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_NacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_Tipo_DocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nro_DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Materno {
            get {
                return this.Ape_MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_MaternoField, value) != true)) {
                    this.Ape_MaternoField = value;
                    this.RaisePropertyChanged("Ape_Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Paterno {
            get {
                return this.Ape_PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_PaternoField, value) != true)) {
                    this.Ape_PaternoField = value;
                    this.RaisePropertyChanged("Ape_Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Nac {
            get {
                return this.Fec_NacField;
            }
            set {
                if ((this.Fec_NacField.Equals(value) != true)) {
                    this.Fec_NacField = value;
                    this.RaisePropertyChanged("Fec_Nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Paciente {
            get {
                return this.Id_PacienteField;
            }
            set {
                if ((this.Id_PacienteField.Equals(value) != true)) {
                    this.Id_PacienteField = value;
                    this.RaisePropertyChanged("Id_Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Tipo_Doc {
            get {
                return this.Id_Tipo_DocField;
            }
            set {
                if ((this.Id_Tipo_DocField.Equals(value) != true)) {
                    this.Id_Tipo_DocField = value;
                    this.RaisePropertyChanged("Id_Tipo_Doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nro_Documento {
            get {
                return this.Nro_DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nro_DocumentoField, value) != true)) {
                    this.Nro_DocumentoField = value;
                    this.RaisePropertyChanged("Nro_Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePaciente.IPacientesService")]
    public interface IPacientesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPacientesService/crearPaciente", ReplyAction="http://tempuri.org/IPacientesService/crearPacienteResponse")]
        TheRevenge.SOAPTest.ServicePaciente.Paciente crearPaciente(TheRevenge.SOAPTest.ServicePaciente.Paciente _paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPacientesService/consultarPaciente", ReplyAction="http://tempuri.org/IPacientesService/consultarPacienteResponse")]
        TheRevenge.SOAPTest.ServicePaciente.Paciente consultarPaciente(int intIdPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPacientesService/actualizarPaciente", ReplyAction="http://tempuri.org/IPacientesService/actualizarPacienteResponse")]
        TheRevenge.SOAPTest.ServicePaciente.Paciente actualizarPaciente(TheRevenge.SOAPTest.ServicePaciente.Paciente _paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPacientesService/eliminarPaciente", ReplyAction="http://tempuri.org/IPacientesService/eliminarPacienteResponse")]
        void eliminarPaciente(int intIdPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPacientesService/listarPaciente", ReplyAction="http://tempuri.org/IPacientesService/listarPacienteResponse")]
        TheRevenge.SOAPTest.ServicePaciente.Paciente[] listarPaciente();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPacientesServiceChannel : TheRevenge.SOAPTest.ServicePaciente.IPacientesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacientesServiceClient : System.ServiceModel.ClientBase<TheRevenge.SOAPTest.ServicePaciente.IPacientesService>, TheRevenge.SOAPTest.ServicePaciente.IPacientesService {
        
        public PacientesServiceClient() {
        }
        
        public PacientesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacientesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TheRevenge.SOAPTest.ServicePaciente.Paciente crearPaciente(TheRevenge.SOAPTest.ServicePaciente.Paciente _paciente) {
            return base.Channel.crearPaciente(_paciente);
        }
        
        public TheRevenge.SOAPTest.ServicePaciente.Paciente consultarPaciente(int intIdPaciente) {
            return base.Channel.consultarPaciente(intIdPaciente);
        }
        
        public TheRevenge.SOAPTest.ServicePaciente.Paciente actualizarPaciente(TheRevenge.SOAPTest.ServicePaciente.Paciente _paciente) {
            return base.Channel.actualizarPaciente(_paciente);
        }
        
        public void eliminarPaciente(int intIdPaciente) {
            base.Channel.eliminarPaciente(intIdPaciente);
        }
        
        public TheRevenge.SOAPTest.ServicePaciente.Paciente[] listarPaciente() {
            return base.Channel.listarPaciente();
        }
    }
}
