
package pe.com.consultorio.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITiposDocService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITiposDocService {


    /**
     * 
     * @return
     *     returns pe.com.consultorio.ws.ArrayOfTipoDocumento
     */
    @WebMethod(operationName = "listarTipo_Documento", action = "http://tempuri.org/ITiposDocService/listarTipo_Documento")
    @WebResult(name = "listarTipo_DocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "listarTipo_Documento", targetNamespace = "http://tempuri.org/", className = "pe.com.consultorio.ws.ListarTipoDocumento")
    @ResponseWrapper(localName = "listarTipo_DocumentoResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.consultorio.ws.ListarTipoDocumentoResponse")
    public ArrayOfTipoDocumento listarTipoDocumento();

}
